# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suimon < Formula
  desc ""
  homepage "https://github.com/bartosian/homebrew-tools"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bartosian/suimon/releases/download/v1.2.1/suimon_Darwin_arm64.tar.gz"
      sha256 "3fec473244b004677d65e79a398a4c4f4e02efb201cbada30340fdc61a73dac3"

      def install
        bin.install "suimon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartosian/suimon/releases/download/v1.2.1/suimon_Darwin_x86_64.tar.gz"
      sha256 "46a8e5478d71f91f12a9b56525b28004bd1c11c0e1255f0e2c2b164da16d4a04"

      def install
        bin.install "suimon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartosian/suimon/releases/download/v1.2.1/suimon_Linux_arm64.tar.gz"
      sha256 "6473641bd7b46273570544a19cd7d6ad15adfe430bde8058253bf0b1c3c2fc58"

      def install
        bin.install "suimon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartosian/suimon/releases/download/v1.2.1/suimon_Linux_x86_64.tar.gz"
      sha256 "cc1b7b718f2afafa41eca74cc30448d31a45d85af9d07fd862edb50e13e3b44e"

      def install
        bin.install "suimon"
      end
    end
  end
end
