# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suimon < Formula
  desc ""
  homepage "https://github.com/bartosian/homebrew-tools"
  version "1.2.3"

  on_macos do
    on_intel do
      url "https://github.com/bartosian/suimon/releases/download/v1.2.3/suimon_Darwin_x86_64.tar.gz"
      sha256 "76c7de7ebdaceeac51e27c2160068d232e5f84d8f6dd33882efa43d0d6f1e3e5"

      def install
        bin.install "suimon"
      end
    end
    on_arm do
      url "https://github.com/bartosian/suimon/releases/download/v1.2.3/suimon_Darwin_arm64.tar.gz"
      sha256 "8b181e9b828246a4fe46769d1789147a5225716363ed28fc11721f3cc3d53dec"

      def install
        bin.install "suimon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bartosian/suimon/releases/download/v1.2.3/suimon_Linux_x86_64.tar.gz"
        sha256 "e636206c37bb55606672656cc3249aa1bf046ef82a8172a4297d6ced79313086"

        def install
          bin.install "suimon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bartosian/suimon/releases/download/v1.2.3/suimon_Linux_arm64.tar.gz"
        sha256 "5a603cd2b210c1a4777ab9faa263b36a391628e855da721985f55a0bda2f1754"

        def install
          bin.install "suimon"
        end
      end
    end
  end
end
